spring.application.name=lab

spring.datasource.jndi-name=java:/jdbc/LabDS
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.current_session_context_class=jta
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT

logging.level.root=DEBUG

spring.mvc.servlet.path=/api

yookassa.base-url=${YOOKASSA_BASE_URL:https://api.yookassa.ru/v3}
yookassa.shop-id=${YOOKASSA_SHOP_ID:1301903}
yookassa.api-key=${YOOKASSA_API_KEY:test_IEOqnyv6X31GfBM7BXi8hiTDnfDCbBLoLbbhx8KSHxo}
yookassa.return-url=${YOOKASSA_RETURN_URL:https://www.example.com/return_url}

ru.ifmo.se.app.jwt-secret=j5v0TR80xzmpyJttl2RLn9bFSFJY51bdEAmnFn8pehpyv6X31GfBM7BXi8hiTDnf
ru.ifmo.se.app.jwt-expiration-ms=86400000