spring.application.name=lab

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lab}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

logging.level.root=DEBUG

server.servlet.context-path=/api

yookassa.base-url=${YOOKASSA_BASE_URL:https://api.yookassa.ru/v3}
yookassa.shop-id=${YOOKASSA_SHOP_ID:1301903}
yookassa.api-key=${YOOKASSA_API_KEY:test_IEOqnyv6X31GfBM7BXi8hiTDnfDCbBLoLbbhx8KSHxo}
yookassa.return-url=${YOOKASSA_RETURN_URL:https://www.example.com/return_url}